const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={theme:localStorage.getItem("theme")||"light",history:JSON.parse(localStorage.getItem("calcHistory")||"[]"),sci:"",angle:"DEG"};
document.body.classList.toggle("dark",state.theme==="dark");
const views={dashboard:"Calculator Dashboard",basic:"Basic Calculator",scientific:"Scientific Calculator",bmi:"BMI Calculator",converter:"Unit Converter",currency:"Currency Converter",age:"Age Calculator",date:"Date Calculator"};
function showView(v){$$(".view").forEach(x=>x.classList.remove("active-view"));$("#"+v).classList.add("active-view");$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===v));$("#pageTitle").textContent=views[v]||"Calculator";$(".sidebar").classList.remove("open");window.scrollTo({top:0,behavior:"smooth"})}
$$(".nav-item").forEach(b=>b.onclick=()=>showView(b.dataset.view));$$("[data-open]").forEach(c=>c.onclick=()=>showView(c.dataset.open));
$("#menuBtn").onclick=()=>$(".sidebar").classList.toggle("open");
$("#themeBtn").onclick=()=>{state.theme=state.theme==="dark"?"light":"dark";document.body.classList.toggle("dark",state.theme==="dark");localStorage.setItem("theme",state.theme);$("#themeBtn").innerHTML=state.theme==="dark"?"☀ <span>Light mode</span>":"☾ <span>Dark mode</span>"};
$("#themeBtn").innerHTML=state.theme==="dark"?"☀ <span>Light mode</span>":"☾ <span>Dark mode</span>";
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2200)}
function saveHistory(expr,result){state.history.unshift({expr,result,time:new Date().toLocaleString()});state.history=state.history.slice(0,30);localStorage.setItem("calcHistory",JSON.stringify(state.history));renderHistory()}
function renderHistory(){let h=$("#historyList");h.innerHTML=state.history.length?state.history.map(x=>`<div class="history-item"><small>${x.time}</small><b>${esc(x.expr)}</b><br>= ${esc(x.result)}</div>`).join(""):"<p class='hint'>No calculations yet.</p>"}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
renderHistory();$("#clearHistory").onclick=()=>{state.history=[];localStorage.removeItem("calcHistory");renderHistory()};
function makeKeys(id,scientific=false){let keys=scientific?["C","⌫","(",")","7","8","9","÷","4","5","6","×","1","2","3","−","0",".","%","+","="]:["C","⌫","%","÷","7","8","9","×","4","5","6","−","1","2","3","+","0",".","="];let box=$("#"+id);box.innerHTML=keys.map(k=>`<button class="${"÷×−+%=".includes(k)?"operator ":""}${k==="="?"equals":""}" data-key="${k}">${k}</button>`).join("")}
makeKeys("basicKeys");makeKeys("sciKeys",true);
let basicExpr="";
function basicPress(k){if(k==="C"){basicExpr="";$("#basicExpression").textContent="";$("#basicDisplay").textContent="0";return}if(k==="⌫"){basicExpr=basicExpr.slice(0,-1)}else if(k==="="){try{let exp=basicExpr.replaceAll("×","*").replaceAll("÷","/").replaceAll("−","-").replace(/%/g,"/100");let r=Function(`"use strict";return (${exp})`)();if(!Number.isFinite(r))throw Error();r=Math.round(r*1e12)/1e12;saveHistory(basicExpr,r);basicExpr=String(r)}catch{toast("Invalid calculation");basicExpr=""}}else basicExpr+=k;$("#basicExpression").textContent=basicExpr;$("#basicDisplay").textContent=basicExpr||"0"}
$("#basicKeys").onclick=e=>e.target.dataset.key&&basicPress(e.target.dataset.key);
document.addEventListener("keydown",e=>{if(["INPUT","SELECT"].includes(document.activeElement.tagName))return;let m={"Enter":"=","Backspace":"⌫","Escape":"C","*":"×","/":"÷","-":"−"};let k=m[e.key]||e.key;if(/^[0-9.%+()=]$/.test(k)||"⌫C×÷−".includes(k)){e.preventDefault();basicPress(k)}});
let sciExpr="";
function sciEval(exp){return Function(`"use strict";return (${exp})`)()}
function sciPress(k){if(k==="C"){sciExpr=""}else if(k==="⌫"){sciExpr=sciExpr.slice(0,-1)}else if(k==="="){try{let e=sciExpr.replaceAll("×","*").replaceAll("÷","/").replaceAll("−","-").replace(/π/g,"Math.PI").replace(/\be\b/g,"Math.E").replace(/(\d+(?:\.\d+)?)%/g,"($1/100)").replace(/(\d+(?:\.\d+)?)\^2/g,"($1**2)");let r=sciEval(e);r=Math.round(r*1e12)/1e12;saveHistory(sciExpr,r);sciExpr=String(r)}catch{toast("Invalid expression");sciExpr=""}}else sciExpr+=k;$("#sciExpression").textContent=sciExpr;$("#sciDisplay").textContent=sciExpr||"0"}
$("#sciKeys").onclick=e=>e.target.dataset.key&&sciPress(e.target.dataset.key);
$$(".sci-tools button[data-fn]").forEach(b=>b.onclick=()=>{let f=b.dataset.fn;if(f==="pi"||f==="e")return sciPress(f==="pi"?"π":"e");if(f==="square")sciExpr+=`^2`;else if(f==="factorial"){let n=Number(sciExpr);if(n<0||n>170||n%1)toast("Use a non-negative integer");else{let r=1;for(let i=2;i<=n;i++)r*=i;sciExpr=String(r)}}else if(f==="sqrt")sciExpr=`Math.sqrt(${sciExpr||0})`;else if(["sin","cos","tan"].includes(f)){let x=Number(sciExpr||0);if(state.angle==="DEG")x=x*Math.PI/180;sciExpr=String(Math[f](x))}else if(f==="log")sciExpr=`Math.log10(${sciExpr||0})`;else if(f==="ln")sciExpr=`Math.log(${sciExpr||0})`;$("#sciExpression").textContent=sciExpr;$("#sciDisplay").textContent=sciExpr||"0"});
$("#angleMode").onclick=()=>{state.angle=state.angle==="DEG"?"RAD":"DEG";$("#angleMode").textContent=state.angle};
$("#bmiUnit").onchange=()=>{$("#heightUnit").textContent=$("#bmiUnit").value==="metric"?"cm":"in";$("#weightUnit").textContent=$("#bmiUnit").value==="metric"?"kg":"lb"};
$("#bmiCalc").onclick=()=>{let h=+$("#height").value,w=+$("#weight").value;if(!h||!w)return toast("Enter height and weight");let bmi=$("#bmiUnit").value==="metric"?w/((h/100)**2):(w*703)/(h*h);bmi=Math.round(bmi*10)/10;let cat=bmi<18.5?"Underweight":bmi<25?"Healthy":bmi<30?"Overweight":"Obesity";$("#bmiResult").textContent=bmi;$("#bmiCategory").textContent=cat;$("#bmiMarker").style.left=Math.min(98,Math.max(1,(bmi/40)*100))+"%"};
const units={length:{m:1,km:1000,cm:.01,mm:.001,mi:1609.344,yd:.9144,ft:.3048,in:.0254},weight:{kg:1,g:.001,mg:.000001,lb:.45359237,oz:.0283495231},area:{m²:1,km²:1e6,ft²:.09290304,acre:4046.8564224,ha:10000},volume:{L:1,mL:.001,m³:1000,gal:3.785411784,qt:.946352946,pint:.473176473},speed:{"m/s":1,"km/h":.277777778,mph:.44704,knot:.514444},data:{B:1,KB:1024,MB:1024**2,GB:1024**3,TB:1024**4},time:{sec:1,min:60,hour:3600,day:86400,week:604800}};
const labels={length:["m","km","cm","mm","mi","yd","ft","in"],weight:["kg","g","mg","lb","oz"],area:["m²","km²","ft²","acre","ha"],volume:["L","mL","m³","gal","qt","pint"],speed:["m/s","km/h","mph","knot"],data:["B","KB","MB","GB","TB"],time:["sec","min","hour","day","week"]};
function populateUnits(){let t=$("#convType").value,a=labels[t];$("#convFrom").innerHTML=a.map(x=>`<option>${x}</option>`).join("");$("#convTo").innerHTML=a.map(x=>`<option>${x}</option>`).join("");$("#convTo").value=a[1]||a[0];convert()}
function convert(){let t=$("#convType").value,v=+$("#convInput").value||0,f=$("#convFrom").value,to=$("#convTo").value;if(t==="temperature"){let c=f==="C"?v:f==="F"?(v-32)*5/9:v-273.15;let r=to==="C"?c:to==="F"?c*9/5+32:c+273.15;$("#convOutput").value=Number(r.toFixed(8))}else{let r=v*units[t][f]/units[t][to];$("#convOutput").value=Number(r.toFixed(10))}}
$("#convType").onchange=populateUnits;$("#convInput").oninput=convert;$("#convFrom").onchange=convert;$("#convTo").onchange=convert;$("#swapConv").onclick=()=>{let a=$("#convFrom").value;$("#convFrom").value=$("#convTo").value;$("#convTo").value=a;convert()};populateUnits();
const currencies={USD:1,INR:83.5,EUR:.92,GBP:.78,JPY:150,AUD:1.52,CAD:1.36};let liveRates={...currencies};
function populateCurrency(){let a=Object.keys(currencies);$("#curFrom").innerHTML=a.map(x=>`<option>${x}</option>`).join("");$("#curTo").innerHTML=a.map(x=>`<option>${x}</option>`).join("");$("#curTo").value="INR";currencyConvert()}
function currencyConvert(){let v=+$("#curInput").value||0,f=$("#curFrom").value,t=$("#curTo").value,r=v/liveRates[f]*liveRates[t];$("#curOutput").value=r.toFixed(4);$("#curSummary").textContent=`${v} ${f} ≈ ${r.toFixed(2)} ${t}`}
async function fetchRates(){try{let res=await fetch("https://api.frankfurter.app/latest?from=USD");if(!res.ok)throw Error();let d=await res.json();liveRates={USD:1,...d.rates};$("#rateStatus").textContent="Live rates";$("#curUpdated").textContent="Rates loaded from a public exchange-rate endpoint.";currencyConvert()}catch{$("#rateStatus").textContent="Fallback rates"}}
$("#curInput").oninput=currencyConvert;$("#curFrom").onchange=currencyConvert;$("#curTo").onchange=currencyConvert;$("#swapCur").onclick=()=>{let a=$("#curFrom").value;$("#curFrom").value=$("#curTo").value;$("#curTo").value=a;currencyConvert()};populateCurrency();fetchRates();
$("#ageCalc").onclick=()=>{let s=$("#dob").value;if(!s)return toast("Choose your birth date");let d=new Date(s+"T00:00:00"),n=new Date();if(d>n)return toast("Birth date cannot be in the future");let y=n.getFullYear()-d.getFullYear(),m=n.getMonth()-d.getMonth(),day=n.getDate()-d.getDate();if(day<0){m--;day+=new Date(n.getFullYear(),n.getMonth(),0).getDate()}if(m<0){y--;m+=12}$("#ageResult").textContent=`${y} years, ${m} months, ${day} days`;let next=new Date(n.getFullYear(),d.getMonth(),d.getDate());if(next<n)next.setFullYear(n.getFullYear()+1);let days=Math.ceil((next-n)/86400000);$("#birthdayResult").textContent=`Next birthday: ${next.toLocaleDateString()} — ${days} day${days===1?"":"s"} away.`};
$$(".tab").forEach(b=>b.onclick=()=>{$$(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#diffForm").classList.toggle("hidden",b.dataset.dateTab!=="diff");$("#addForm").classList.toggle("hidden",b.dataset.dateTab!=="add")});
$("#dateDiff").onclick=()=>{let a=new Date($("#dateStart").value),b=new Date($("#dateEnd").value);if(isNaN(a)||isNaN(b))return toast("Choose both dates");let days=Math.round((b-a)/86400000),abs=Math.abs(days);$("#dateResult").textContent=`${abs} day${abs===1?"":"s"}`;$("#dateSubResult").textContent=`${Math.floor(abs/7)} weeks and ${abs%7} days${days<0?" (end date is earlier)":""}.`};
$("#dateAdd").onclick=()=>{let d=new Date($("#dateBase").value),days=+$("#dateDays").value;if(isNaN(d)||isNaN(days))return toast("Enter a date and number of days");d.setDate(d.getDate()+days);$("#dateResult").textContent=d.toLocaleDateString(undefined,{weekday:"long",year:"numeric",month:"long",day:"numeric"});$("#dateSubResult").textContent=`${Math.abs(days)} days ${days>=0?"after":"before"} the selected date.`};
$("#historyBtn").onclick=()=>{showView("basic");$("#historyList").scrollIntoView({behavior:"smooth"})};
document.querySelectorAll("input[type=date]").forEach(x=>x.max=new Date().toISOString().slice(0,10));